server:
  port: 8080
  tomcat:
    basedir:
#    accesslog:
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/avatar?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    initial-size: 50
    max-active: 50
    min-idle: 50


mybatis:
  typeAliasesPackage: com.walker.domain
  mapperLocations: classpath:mapper/*.xml