server:
  port: 8089

spring:
  application:
    name: springboot-eureka-client

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include: "*"