server:
  port: 8089

spring:
  application:
    name: springboot-eureka-client

eureka:
  client:
    serviceUrl:
      #指定到peer1机器上
      defaultZone: http://peer1:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include: "*"